appname: "SessionCookie"
charset: "UTF-8"

template: "simple"
session: "Cookie"

engines:
    session:
        Cookie:
            secret_key: "Shhhhss... Secret!!!"
            default_duration: 86400
